# Generated by Django 6.0.2 on 2026-02-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdataset',
            name='equipment_type_distribution',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
